[package]
name = "cli"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "cli"
path = "src/lib.rs"

[dependencies]
eyre = { workspace = true, default-features = false }
pico-args = {workspace = true}
lool = {workspace = true}