allow-branch = ["master"]
sign-commit = true
sign-tag = true
pre-release-commit-message = "release: 🔖 v{{version}}"
tag-message = "release: 🔖 v{{version}}"
tag-prefix = ""
consolidate-commits = false
tag-name = "v{{version}}"
push = false
publish = false