version: '3'

tasks:
  dev:
    desc: 👨🏻‍💻 run ids in «dev» mode
    cmds:
      - cargo watch -c -x "run --"

  build:
    desc: ⚡ build ids «release»
    cmds:
      - cargo build --release
      - python check_size.py

  fmt:
    desc: 🎨 format ids
    cmds:
      - cargo +nightly fmt --all
  
  fmt:check:
    desc: 🎨 check ids formatting
    cmds:
      - cargo +nightly fmt --all --check

  lint:
    desc: 🧶 lint ids
    cmds:
      - cargo clippy --fix --workspace --allow-staged
  
  lint:check:
    desc: 🧶 check ids linting
    cmds:
      - cargo clippy --workspace

  fmt+lint:
    desc: 🎨🧶 format and lint ids
    cmds:
      - task fmt
      - git add .
      - task lint