version: 3

tasks:
  build:
    desc: ⚡ build ui
    cmds:
      - bun vite build

  dev:
    desc: 🚀 start dev server
    cmds:
      - bun vite --clearScreen false

  preview:
    desc: 🎉 preview ui
    cmds:
      - bun vite preview

  lint:
    desc: 🧹 lint ui
    cmds:
      - bun biome lint